# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51126c8fdbda087c387378f8c4412af00df97583c0eb09397620225649113a3ca917ce1a06f7f8255a4e2d220b0c46ccef0610f2145168e2e914a99c9b6bd0bd

test:
  secret_key_base: 4c72f38b0b6da45c0c2192ad532af75b4d3a49468ed14d0aac8a3b174912b7ad89694fe9be6799acd43658bd573fb485e23931da9f25e344f5da0e42aaf3972e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
